[build]
  # comando que o Netlify vai executar
  command = "npm run build"
  # diretório que será publicado
  publish = "dist/public"

# Redirecionamento para suportar SPA (React Router, wouter, etc.)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200